### ISSUE TITLE
Feat: update claim function

### ISSUE THREAD

**Issue by kinspotting** [PrimeDAO/contracts#141]
Enable the contract to claim a given number of seed tokens, rather than only all of them

Also consider that claimer is the `msg.sender` and the parameter passed is the `amount` of tokens to be claimed

**Comment by kinspotting** [comment]
Research- convert `daysVested` to `secondsVested`

**Comment by codebuster22** [comment]
Problems with current Claim Process:-
1) It transfers the tokenLock.fee everytime anyone claim. The tokenLock.fee is the total fee the total seedAmount. For Example. If a user buys 100 tokens. The fee will 2 tokens. Now if the target is reached. The user can now claim but not the full amount.So if the user claim after vestingCliff + 1 month. The fee we transfer is 2. Then the user again claims after vestingCliff+ 2 month again the fee we transfer is 2 tokens. This will lead to scarcity of token at contract.

2) No way to get total claimable tokens for a user.

3) No way to claim tokens when a user have total claimable tokens < amountVestedPerSecond.

4) no way to know total buyable tokens after fees calculation.

Solution:-

1) Only transfer tokenLock.fee for the first claim.

2) We need a function to calculate the amount of claimable tokens. This will help for the front end. The input we need is maximum amount of tokens they want to claim. Because they cannot claim exact amount they want due to floating point values we get for secondsClaimed.

3) Improvement in claimLock to check for the remaining tokens and make decision according to it 

4) Create a function to calculate total buyable tokens or, to have a variable where we store buyable tokens after subtracting fees for total sale.

Note:- Currently working on it.
